# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2020-01-02 06:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0002_todo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='message',
        ),
        migrations.AddField(
            model_name='todo',
            name='title',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='todo',
            name='name',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
