# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2020-01-07 08:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0005_client'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='message',
            new_name='details',
        ),
        migrations.RenameField(
            model_name='client',
            old_name='mobile',
            new_name='title',
        ),
    ]
