# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2020-01-09 06:44
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0006_auto_20200107_0803'),
    ]

    operations = [
        migrations.DeleteModel(
            name='client',
        ),
        migrations.AddField(
            model_name='todo',
            name='date',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
