# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2020-01-09 07:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0008_auto_20200109_0651'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='dt',
        ),
    ]
