# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2020-01-09 08:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0009_remove_todo_dt'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='dt',
            field=models.DateField(blank=True, null=True, verbose_name='Date'),
        ),
    ]
