# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2020-01-09 08:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0010_todo_dt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='dt',
        ),
        migrations.AlterField(
            model_name='todo',
            name='name',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='todo',
            name='title',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
